#!/usr/bin/env ruby
# frozen_string_literal: true

# Give the iOS project the same two-flavour split Android already has.
#
#   consumer → com.myweli.app  "MyWeli"      (lib/main.dart)
#   pro      → com.myweli.pro  "MyWeli Pro"  (lib/main_pro.dart)
#
# Scripted rather than hand-edited: project.pbxproj is a UUID-keyed object
# graph, and an edit that looks right in a diff can yield a project Xcode opens
# happily but xcodebuild rejects. This uses the `xcodeproj` gem — the same
# library CocoaPods uses — so the result is structurally valid by construction.
#
# IDEMPOTENT: re-running is a no-op. That matters because CocoaPods rewrites
# parts of the project on every `pod install`.
#
#   cd mobile/ios && ruby tool/setup_flavours.rb && pod install
#
# Design: docs/design/mobile-ios-flavours.md

require 'xcodeproj'
require 'fileutils'

FLAVOURS = {
  'consumer' => { bundle_id: 'com.myweli.app', display_name: 'MyWeli' },
  'pro'      => { bundle_id: 'com.myweli.pro', display_name: 'MyWeli Pro' },
}.freeze

# Flutter's contract: <Action>-<flavour>. Run/Test/Analyze take Debug, the
# profile action takes Profile, archive takes Release.
BASES = %w[Debug Profile Release].freeze

project_path = File.expand_path('../Runner.xcodeproj', __dir__)
project = Xcodeproj::Project.open(project_path)

runner = project.targets.find { |t| t.name == 'Runner' } or abort 'no Runner target'
tests  = project.targets.find { |t| t.name == 'RunnerTests' }

# `owner` is the project or a target — both hold build_configurations, but only
# a target answers `.project`, so it is passed in rather than derived.
def clone_config(project, owner, base_name, new_name)
  return owner.build_configurations.find { |c| c.name == new_name } if
    owner.build_configurations.any? { |c| c.name == new_name }

  base = owner.build_configurations.find { |c| c.name == base_name }
  raise "missing base configuration #{base_name}" if base.nil?

  cfg = project.new(Xcodeproj::Project::Object::XCBuildConfiguration)
  cfg.name = new_name
  # Deep-copy so later edits to one flavour cannot reach through into another.
  cfg.build_settings = Marshal.load(Marshal.dump(base.build_settings))
  # Carry the xcconfig chain (Flutter's Generated.xcconfig + the Pods xcconfig).
  # Authoring settings from scratch instead would silently drop whatever Flutter
  # adds in a future release.
  cfg.base_configuration_reference = base.base_configuration_reference
  owner.build_configurations << cfg
  cfg
end

FLAVOURS.each do |flavour, meta|
  BASES.each do |base|
    name = "#{base}-#{flavour}"

    # Project level first: target configurations resolve against it.
    clone_config(project, project, base, name)

    cfg = clone_config(project, runner, base, name)
    cfg.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = meta[:bundle_id]
    # Info.plist reads $(APP_DISPLAY_NAME) — the analogue of Android's
    # resValue("string", "app_name", …).
    cfg.build_settings['APP_DISPLAY_NAME'] = meta[:display_name]

    next if tests.nil?

    # The test target needs matching configurations or each scheme's Test
    # action fails to resolve one. Its bundle id stays derived from the host.
    tcfg = clone_config(project, tests, base, name)
    tcfg.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = "#{meta[:bundle_id]}.RunnerTests"
    tcfg.build_settings['TEST_HOST'] =
      '$(BUILT_PRODUCTS_DIR)/Runner.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/Runner'
  end
end

# The pre-existing configurations describe the flavourless build. Leave the
# bundle id alone there EXCEPT to retire the personal-namespace identifier,
# which was never published.
%w[Debug Profile Release].each do |base|
  cfg = runner.build_configurations.find { |c| c.name == base }
  next if cfg.nil?

  cfg.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'com.myweli.app'
  cfg.build_settings['APP_DISPLAY_NAME'] = 'MyWeli'
end

# --- per-flavour xcconfig ---------------------------------------------------
# CocoaPods generates one xcconfig per build configuration
# (Pods-Runner.debug-consumer.xcconfig, …) but only wires it up when the
# configuration has no custom base config. Ours DO have one — Flutter's — so
# CocoaPods bows out with "did not set the base configuration", and without
# these files the pods are simply absent from every flavour build.
#
# So each flavour gets the same two-line file Flutter itself uses, pointing at
# its own Pods xcconfig. `#include?` (optional) matches Flutter's own style:
# the project must still open before the first `pod install`.
flutter_group = project.main_group.find_subpath('Flutter', true)

FLAVOURS.each_key do |flavour|
  BASES.each do |base|
    name = "#{base}-#{flavour}"
    path = File.expand_path("../Flutter/#{name}.xcconfig", __dir__)

    File.write(path, <<~XCCONFIG)
      // Generated by tool/setup_flavours.rb — see docs/design/mobile-ios-flavours.md
      #include? "Pods/Target Support Files/Pods-Runner/Pods-Runner.#{base.downcase}-#{flavour}.xcconfig"
      #include "Generated.xcconfig"
    XCCONFIG

    # The `Flutter` group is VIRTUAL — it has no path of its own — so a
    # <group>-relative reference resolves against the project root (ios/), not
    # ios/Flutter/. The path must carry the folder, exactly as the stock
    # Flutter/Debug.xcconfig reference does. Getting this wrong yields
    # "Unable to open base configuration reference file" at build time, with
    # the project still opening fine in Xcode.
    rel = "Flutter/#{name}.xcconfig"
    # Drop any earlier reference that lacked the prefix, so a re-run repairs
    # rather than accumulates.
    flutter_group.files.select { |f| f.path == "#{name}.xcconfig" }.each(&:remove_from_project)

    ref = flutter_group.files.find { |f| f.path == rel } || flutter_group.new_file(rel)
    ref.path = rel
    ref.source_tree = '<group>'

    [project, runner].compact.each do |owner|
      cfg = owner.build_configurations.find { |c| c.name == name }
      cfg.base_configuration_reference = ref unless cfg.nil?
    end

    # RunnerTests needs its OWN file, not Runner's.
    #
    # It used to share the one above, and that file includes
    # Pods-Runner.<config>.xcconfig — a different target's. So `pod install`
    # warned, on all six configurations, that it "did not set the base
    # configuration" for RunnerTests, and the comment at the top of this script
    # claiming the test target resolves its configuration was simply false.
    # Nothing runs the native tests today, so it was latent rather than live —
    # which is exactly how it survived.
    next if tests.nil?

    tname = "#{name}-tests"
    File.write(File.expand_path("../Flutter/#{tname}.xcconfig", __dir__), <<~XCCONFIG)
      // Generated by tool/setup_flavours.rb — see docs/design/mobile-ios-flavours.md
      #include? "Pods/Target Support Files/Pods-RunnerTests/Pods-RunnerTests.#{base.downcase}-#{flavour}.xcconfig"
      #include "Generated.xcconfig"
    XCCONFIG

    trel = "Flutter/#{tname}.xcconfig"
    tref = flutter_group.files.find { |f| f.path == trel } || flutter_group.new_file(trel)
    tref.path = trel
    tref.source_tree = '<group>'

    tcfg = tests.build_configurations.find { |c| c.name == name }
    tcfg.base_configuration_reference = tref unless tcfg.nil?
  end
end

# --- deployment target -------------------------------------------------------
# The Podfile has said `platform :ios, '15.0'` all along while every one of the
# project's NINE build configurations said **13.0**. CocoaPods hid the split: it
# applies the Podfile platform to the POD targets and leaves the app target
# alone, so the mismatch never had to be resolved and the app built anyway.
#
# Flutter 3.44 adds Swift Package Manager integration, and SPM checks the APP
# target directly:
#
#   The package product 'firebase-core' requires minimum platform version 15.0
#   for the iOS platform, but this target supports 13.0
#
# So the Podfile was aspirational and the project was the truth. Set it here,
# where the rest of the project's configuration is already owned, so it applies
# to the flavour configurations too — those are CLONES of the base ones, and a
# value fixed only by hand in Xcode would be silently re-inherited on the next
# clone.
#
# 15.0 rather than a rounder number because it is what firebase-core and
# firebase-messaging actually demand, and it is what the Podfile already claimed.
DEPLOYMENT_TARGET = '15.0'

[runner, tests].compact.each do |target|
  target.build_configurations.each do |cfg|
    cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = DEPLOYMENT_TARGET
  end
end
project.build_configurations.each do |cfg|
  cfg.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = DEPLOYMENT_TARGET
end

# --- APNs entitlements per configuration -------------------------------------
# Runner.entitlements existed for months with ZERO CODE_SIGN_ENTITLEMENTS
# references, so the built app carried no `aps-environment` and iOS never issued
# an APNs token. Every bit of Apple/Firebase setup would have looked correct and
# push would still have been dead.
#
# Debug/Profile -> development (sandbox APNs), Release -> production. That split
# is not cosmetic: a build signed `development` gets a SANDBOX token, and a
# production FCM send to it is silently dropped.
ENTITLEMENTS = {
  'Debug'   => 'Runner/Runner.entitlements',
  'Profile' => 'Runner/Runner.entitlements',
  'Release' => 'Runner/RunnerRelease.entitlements',
}.freeze

runner.build_configurations.each do |cfg|
  base = cfg.name.split('-').first
  path = ENTITLEMENTS[base]
  next if path.nil?

  cfg.build_settings['CODE_SIGN_ENTITLEMENTS'] = path
end

# --- Firebase config per flavour ---------------------------------------------
# `Firebase.initializeApp()` takes no options on iOS (firebase_bootstrap.dart:31),
# so it reads GoogleService-Info.plist FROM THE APP BUNDLE. Nothing puts it
# there by default, and the two flavours need different files — consumer and pro
# are separate Firebase apps with different bundle ids and API keys.
#
# A run-script phase copies the right one, keyed off $CONFIGURATION
# ("Debug-consumer" -> "consumer"). The flavourless configurations yield
# "Debug"/"Release", which match no directory, so the `-f` guard skips them —
# the same "only when the config is actually present" posture as the Android
# Gradle wiring, which keeps a fresh clone building before Firebase exists.
PHASE_NAME = 'Copy Firebase config (per flavour)'
runner.build_phases.reject! { |ph| ph.respond_to?(:name) && ph.name == PHASE_NAME }
phase = project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
phase.name = PHASE_NAME
phase.shell_path = '/bin/sh'
phase.shell_script = <<~SH
  # Generated by tool/setup_flavours.rb — docs/design/mobile-ios-flavours.md
  FLAVOUR="${CONFIGURATION##*-}"
  SRC="${SRCROOT}/config/${FLAVOUR}/GoogleService-Info.plist"
  if [ -f "$SRC" ]; then
    cp "$SRC" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist"
    echo "note: Firebase config for flavour '${FLAVOUR}'"
  else
    echo "note: no Firebase config for '${FLAVOUR}' — skipping (push will be inert)"
  fi
SH
# Must run AFTER the app bundle exists, so append rather than insert.
runner.build_phases << phase

project.save

# --- schemes ----------------------------------------------------------------
# Shared, so they are committed and every machine sees the same mapping.
schemes_dir = File.join(project_path, 'xcshareddata', 'xcschemes')
FileUtils.mkdir_p(schemes_dir)

FLAVOURS.each_key do |flavour|
  scheme = Xcodeproj::XCScheme.new
  scheme.add_build_target(runner)
  scheme.set_launch_target(runner)
  scheme.add_test_target(tests) unless tests.nil?

  scheme.build_action.parallelize_buildables = true
  scheme.launch_action.build_configuration   = "Debug-#{flavour}"
  scheme.test_action.build_configuration     = "Debug-#{flavour}"
  scheme.analyze_action.build_configuration  = "Debug-#{flavour}"
  scheme.profile_action.build_configuration  = "Profile-#{flavour}"
  scheme.archive_action.build_configuration  = "Release-#{flavour}"

  scheme.save_as(project_path, flavour, true) # true = shared
end

puts "✓ configurations: #{runner.build_configurations.map(&:name).sort.join(', ')}"
puts "✓ schemes: #{FLAVOURS.keys.join(', ')} (+ Runner)"
puts
puts 'NEXT: run `pod install` in mobile/ios.'
puts 'CocoaPods writes one xcconfig per build configuration; without it the new'
puts 'ones fail with "Unable to open base configuration reference file".'
