/// The salon client base (module `clients`, slice C1 —
/// docs/design/clients-c1.md). Each client is a `Map` in the `SalonClient`
/// DTO shape (docs/api/openapi.yaml): `{id, providerId, userId?, displayName,
/// phone?, tags, lastVisitAt?, createdAt}`. Notes are `{id, clientId,
/// authorAccountId, body, createdAt}`. Rows are DERIVED from bookings
/// (docs/modules/clients.md — "derived, not entered"): [upsertFromBooking]
/// keeps the base fresh; the 0024 migration backfills history.
abstract interface class ClientsRepository {
  /// Paginated salon-scoped list, `last_visit_at DESC NULLS LAST`.
  /// [query] matches the display name (case-insensitive substring) or the
  /// phone (digit-suffix); [tag] filters exact.
  Future<({List<Map<String, dynamic>> items, int total})> list(
    String providerId, {
    String? query,
    String? tag,
    required int page,
    required int pageSize,
  });

  /// Distinct tags across the salon's base (for the filter chips).
  Future<List<String>> tagsFor(String providerId);

  /// Scoped by provider — a foreign clientId resolves to null (404, no leak).
  Future<Map<String, dynamic>?> byId(String providerId, String clientId);

  Future<Map<String, dynamic>?> byPhone(String providerId, String phone);

  Future<Map<String, dynamic>?> byUserId(String providerId, String userId);

  /// Persist a new client row (id generated by the caller).
  Future<Map<String, dynamic>> create(Map<String, dynamic> client);

  /// Replace the tag set. Null when the client doesn't exist (scoped).
  Future<Map<String, dynamic>?> updateTags(
    String providerId,
    String clientId,
    List<String> tags,
  );

  /// Bump `lastVisitAt` if [visitAt] is later than the stored value.
  Future<void> touchLastVisit(
    String providerId,
    String clientId,
    DateTime visitAt,
  );

  // ---- Notes ---------------------------------------------------------------

  Future<Map<String, dynamic>> addNote(Map<String, dynamic> note);

  /// Newest first.
  Future<List<Map<String, dynamic>>> notesFor(String clientId);

  Future<Map<String, dynamic>?> noteById(String clientId, String noteId);

  Future<bool> deleteNote(String clientId, String noteId);

  // ---- Privacy (threat T48) ------------------------------------------------

  /// Deleted-account anonymization across EVERY salon: unlink `userId`, wipe
  /// name/phone; tags, notes and aggregates stay (no longer identifying).
  Future<void> anonymizeUser(String userId);
}

class InMemoryClientsRepository implements ClientsRepository {
  final List<Map<String, dynamic>> _clients = [];
  final List<Map<String, dynamic>> _notes = [];

  static String _digits(String s) => s.replaceAll(RegExp(r'[^0-9]'), '');

  @override
  Future<({List<Map<String, dynamic>> items, int total})> list(
    String providerId, {
    String? query,
    String? tag,
    required int page,
    required int pageSize,
  }) async {
    final q = query?.trim().toLowerCase();
    final qDigits = q == null ? '' : _digits(q);
    final filtered =
        _clients.where((c) => c['providerId'] == providerId).where((c) {
          if (tag != null && tag.isNotEmpty) {
            if (!(c['tags'] as List).contains(tag)) return false;
          }
          if (q == null || q.isEmpty) return true;
          final name = (c['displayName'] as String).toLowerCase();
          if (name.contains(q)) return true;
          final phone = c['phone'] as String?;
          return qDigits.length >= 2 &&
              phone != null &&
              _digits(phone).contains(qDigits);
        }).toList()..sort((a, b) {
          final la = a['lastVisitAt'] as String?;
          final lb = b['lastVisitAt'] as String?;
          if (la == null && lb == null) return 0;
          if (la == null) return 1; // NULLS LAST
          if (lb == null) return -1;
          return lb.compareTo(la);
        });
    final start = (page - 1) * pageSize;
    final items = start >= filtered.length
        ? <Map<String, dynamic>>[]
        : filtered.sublist(start, (start + pageSize).clamp(0, filtered.length));
    return (items: [for (final c in items) Map.of(c)], total: filtered.length);
  }

  @override
  Future<List<String>> tagsFor(String providerId) async {
    final tags = <String>{};
    for (final c in _clients) {
      if (c['providerId'] == providerId) {
        tags.addAll((c['tags'] as List).cast<String>());
      }
    }
    return tags.toList()..sort();
  }

  @override
  Future<Map<String, dynamic>?> byId(String providerId, String clientId) async {
    for (final c in _clients) {
      if (c['id'] == clientId && c['providerId'] == providerId) {
        return Map.of(c);
      }
    }
    return null;
  }

  @override
  Future<Map<String, dynamic>?> byPhone(String providerId, String phone) async {
    for (final c in _clients) {
      if (c['providerId'] == providerId && c['phone'] == phone) {
        return Map.of(c);
      }
    }
    return null;
  }

  @override
  Future<Map<String, dynamic>?> byUserId(
    String providerId,
    String userId,
  ) async {
    for (final c in _clients) {
      if (c['providerId'] == providerId && c['userId'] == userId) {
        return Map.of(c);
      }
    }
    return null;
  }

  @override
  Future<Map<String, dynamic>> create(Map<String, dynamic> client) async {
    _clients.add(Map.of(client));
    return Map.of(client);
  }

  @override
  Future<Map<String, dynamic>?> updateTags(
    String providerId,
    String clientId,
    List<String> tags,
  ) async {
    for (final c in _clients) {
      if (c['id'] == clientId && c['providerId'] == providerId) {
        c['tags'] = List<String>.of(tags);
        return Map.of(c);
      }
    }
    return null;
  }

  @override
  Future<void> touchLastVisit(
    String providerId,
    String clientId,
    DateTime visitAt,
  ) async {
    for (final c in _clients) {
      if (c['id'] == clientId && c['providerId'] == providerId) {
        final current = c['lastVisitAt'] as String?;
        final iso = visitAt.toUtc().toIso8601String();
        if (current == null || current.compareTo(iso) < 0) {
          c['lastVisitAt'] = iso;
        }
      }
    }
  }

  @override
  Future<Map<String, dynamic>> addNote(Map<String, dynamic> note) async {
    _notes.add(Map.of(note));
    return Map.of(note);
  }

  @override
  Future<List<Map<String, dynamic>>> notesFor(String clientId) async {
    return [
      for (final n in _notes.reversed)
        if (n['clientId'] == clientId) Map.of(n),
    ];
  }

  @override
  Future<Map<String, dynamic>?> noteById(String clientId, String noteId) async {
    for (final n in _notes) {
      if (n['id'] == noteId && n['clientId'] == clientId) return Map.of(n);
    }
    return null;
  }

  @override
  Future<bool> deleteNote(String clientId, String noteId) async {
    final before = _notes.length;
    _notes.removeWhere((n) => n['id'] == noteId && n['clientId'] == clientId);
    return _notes.length < before;
  }

  @override
  Future<void> anonymizeUser(String userId) async {
    for (final c in _clients) {
      if (c['userId'] == userId) {
        c['userId'] = null;
        c['displayName'] = 'Client';
        c['phone'] = null;
      }
    }
  }
}
